#!/bin/bash
set -e
set -x

export GOPATH=$PWD

VERSION=$(cat version/number)

pushd src/github.com/bluemixgaragelondon/cf-blue-green-deploy
  ./script/build
popd

tar -C src/github.com/bluemixgaragelondon/cf-blue-green-deploy/artefacts -zcvf blue-green-deploy-$VERSION.tar.gz .

mv blue-green-deploy-$VERSION.tar.gz artefacts

