#!/bin/bash
set -e -x

# Install Go 
sudo apt-get update 
sudo apt-get -y install golang
export GOROOT=$HOME/.go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Update the directory structure of the extract to be go-friendly
mkdir -p go/src/github.com/bluemixgaragelondon/cf-blue-green-deploy
shopt -s dotglob nullglob extglob
mv !(go) go/src/github.com/bluemixgaragelondon/cf-blue-green-deploy 
cd go 

# Run the build
export GOPATH=$PWD
export PLUGIN_VERSION=$(cat version/number)

pushd src/github.com/bluemixgaragelondon/cf-blue-green-deploy
  . script/with_env
  ./script/build
popd

