#!/bin/bash -e

. script/with_env

PLUGIN_NAME="${PLUGIN_NAME:?Must be set in .env}"
PLUGIN_VERSION="${PLUGIN_VERSION:?Must be set in .env}"

script/deps
script/test

targets=(
  "osx darwin amd64"
  "linux32 linux 386"
  "linux64 linux amd64"
)

for target in "${targets[@]}"
do
  read platform goos goarch <<< $target

  binary_name="${PLUGIN_NAME}.$platform"
  GOOS="$goos" GOARCH="$goarch" go build -ldflags "-X main.PluginVersion=${PLUGIN_VERSION}" -o "$binary_name"
  mv "$binary_name" artefacts
done

cp .env artefacts
