#!/bin/bash

# On IBM Cloud, some commands are of the form 'bx [stuff]', and others are 'bx cf [stuff]'
cf_platform_command=${1:-cf}
cf_command="${1:-} cf"

login_to_bluemix() {
  CF_URL="${CF_URL:?must be defined}"
  CF_PASSWORD="${CF_PASSWORD:=$CF_TOKEN}"

  CF_ORG="${CF_ORG:?must be defined}"
  CF_SPACE="${CF_SPACE:?must be defined}"

  set -o pipefail
  if ! $cf_command apps | grep -e "org ${CF_ORG}.*space ${CF_SPACE}.*as ${CF_USERNAME}" >/dev/null
  then
    if [ -n "${CF_PASSWORD+1}" ]
    then
      CF_USERNAME="${CF_USERNAME:?must be defined}"
      $cf_platform_command login -a "$CF_URL" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORG" -s "$CF_SPACE" || $cf_command create-space "$CF_SPACE"
    else
      API_KEY="${API_KEY:?must be defined since CF_PASSWORD is not set}"
      $cf_platform_command login -a "$CF_URL" --apikey "$API_KEY" -o "$CF_ORG" -s "$CF_SPACE" || $cf_command create-space "$CF_SPACE"
    fi
    $cf_platform_command target -s "$CF_SPACE"
  fi
  set +o pipefail
}

uninstall_plugin() {
  local plugin_name="$1"

  plugin_not_installed? "$plugin_name" || $cf_platform_command uninstall-plugin "$plugin_name"
}

plugin_not_installed?() {
  local plugin_name="$1"

  ! grep "$plugin_name" <<< "$($cf_platform_command plugins)" >&-
}

install_plugin() {
  local plugin_name="$1"

  $cf_platform_command install-plugin -f "artefacts/${plugin_name}.$(platform_name)" 
}

push_example_apps() {
  pushd acceptance/app
    login_to_bluemix
    local app_name="$1"
    local app_host_name="$2"
    $cf_command push "${app_name}-old"
    $cf_command push "$app_name"
    $cf_command map-route "$app_name" eu-gb.mybluemix.net -n "$app_host_name"
  popd
}

platform_name() {
  platform=$(go version | awk '{print $4}' | sed 's|/| |')
  case $platform in
    "darwin amd64")
      echo "osx"
      ;;
    "linux 386")
      echo "linux32"
      ;;
    "linux amd64")
      echo "linux64"
      ;;
    "windows 386")
      echo "win32"
      ;;
    "windows amd64")
      echo "win64"
      ;;
  esac
}

get_go_package_dir() {
  echo "$GOPATH" | cut -d : -f 1
}
