#!/bin/bash -ex

REPO=~/workspace/garage-cf-plugins
PLUGIN_NAME=blue-green-deploy

script/test

# plugin targets (GOOS, GOARCH)
osx=(darwin amd64)
linux32=(linux 386)
linux64=(linux amd64)

for target in osx linux32 linux64; do
  build_options=($(eval echo \${$target[@]}))
  goos=${build_options[0]}
  goarch=${build_options[1]}

  build_output="$PLUGIN_NAME.$target"
  GOOS=$goos GOARCH=$goarch go build -o "$build_output"

  sha1=$(shasum "$build_output" | awk '{print $1}')
  jq_replace='(.plugins[] | select(.name == "'"$PLUGIN_NAME"'") | .binaries[] | select(.platform == "'"$target"'") ) |= . + {"checksum": "'$sha1'"}'

  jq "$jq_replace" "$REPO/public/list" > temp_list
  mv temp_list "$REPO/public/list"

  cp "$build_output" "$REPO/public/bin/$target"
done

pushd $REPO
  git add -A
  git commit -v
  git fetch
  git rebase origin/master
  git push
popd

echo "Deploy successful"
