#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

CF_CLI_VERSION="v6.28.0"

 . script/common
GO_PACKAGE_PATH=$(get_go_package_dir)

main() {
  # go get fails because of generated deps
  go get -t || true
  # sort out those generated deps
  cf_cli_set_version
  cf_cli_generate_language_resources
}

cf_cli_set_version() {
  pushd "$GO_PACKAGE_PATH/src/code.cloudfoundry.org/cli"
    git fetch
    git checkout -f "$CF_CLI_VERSION"
  popd
}

cf_cli_generate_language_resources() {
  pushd "$GO_PACKAGE_PATH/src/code.cloudfoundry.org/cli"
    bin/generate-language-resources
  popd
}

main
