#!/bin/bash -e

APP_PKG_NAME="hub.jazz.net/git/bluemixgarage/cf-blue-green-deploy"
ARGS="$@"

main() {
  . script/with_env
  install_test_dependencies

  within_app use_vendored_packages
  within_app run_tests
  within_app prepare_code_coverage_results
}

install_test_dependencies() {
  which godep > /dev/null 2>&1 || go get github.com/tools/godep
  which ginkgo > /dev/null 2>&1|| go get github.com/onsi/ginkgo/ginkgo
  go tool | grep cover > /dev/null 2>&1 || go get golang.org/x/tools/cmd/cover
}

within_app() {
  pushd "${GOPATH}/src/${APP_PKG_NAME}" >/dev/null
  "$@"
  popd >/dev/null
}

use_vendored_packages() {
    godep restore
}

run_tests() {
  ginkgo $ARGS -r -randomizeAllSpecs
}

prepare_code_coverage_results() {
	run_tests -cover > /dev/null 2>&1
  find . -type f -iname "*.coverprofile" | while read; do
    go tool cover -html="$REPLY" -o="$REPLY.html"
    mv "$REPLY.html" coverage
    rm "$REPLY"
  done

  echo "Test coverage details are in the coverage folder."
}

main
