#!/bin/bash -e

GINKGO_ARGS=($@)

main() {
  . script/with_env
  install_test_dependencies

  within_app script/setup
  within_app run_tests
  within_app prepare_code_coverage_results
}

install_test_dependencies() {
  if ! [ -d "$GOPATH"/src/github.com/smarterclayton/godep ]
  then
    go get -d github.com/smarterclayton/godep
    pushd "$GOPATH"/src/github.com/smarterclayton/godep
      git checkout handle_large_files
      go install
    popd
  fi
  which ginkgo > /dev/null 2>&1|| go get github.com/onsi/ginkgo/ginkgo
  go tool | grep cover > /dev/null 2>&1 || go get golang.org/x/tools/cmd/cover
}

within_app() {
  pushd "${GOPATH}/src/${APP_PKG_NAME}" >/dev/null
  "$@"
  popd >/dev/null
}

run_tests() {
  GOPATH="$PWD/Godeps/_workspace:$GOPATH" ginkgo ${GINKGO_ARGS[*]} -r -randomizeAllSpecs
}

prepare_code_coverage_results() {
  run_tests -cover > /dev/null 2>&1
  find . -type f -iname "*.coverprofile" | while read; do
    go tool cover -html="$REPLY" -o="$REPLY.html"
    mv "$REPLY.html" coverage
    rm "$REPLY"
  done

  echo "Test coverage details are in the coverage folder."
}

main
