#!/bin/bash -e

GINKGO_ARGS=($@)

. script/common
GO_PACKAGE_PATH=$(get_go_package_dir)

main() {
  . script/with_env
  install_test_dependencies

  within_app run_tests 

  within_app prepare_code_coverage_results
}

install_test_dependencies() {
  which ginkgo > /dev/null 2>&1|| go get github.com/onsi/ginkgo/ginkgo
  go tool | grep cover > /dev/null 2>&1 || go get golang.org/x/tools/cmd/cover
}

within_app() {
  pushd "${GO_PACKAGE_PATH}/src/${APP_PKG_NAME}" >/dev/null
  "$@"
  popd >/dev/null
}

run_tests() {
		ginkgo ${GINKGO_ARGS[*]} "$@" -r -randomizeAllSpecs

    rm -rf test-results/
    mkdir -p test-results

    find . -path ./test-results -prune -o -type f -iname "*junit.xml" -exec  mv {} test-results \;

    echo "Test reports are in the test-results folder."
}

prepare_code_coverage_results() {
  run_tests -cover > /dev/null 2>&1
  find . -type f -iname "*.coverprofile" | while read; do
    go tool cover -html="$REPLY" -o="$REPLY.html"
    mv "$REPLY.html" coverage
    rm "$REPLY"
  done

  echo "Test coverage details are in the coverage folder."

  
}

main
