#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

CF_CLI_VERSION="v6.11.2"

main() {
  go get -u github.com/onsi/ginkgo/ginkgo
  go get -u github.com/onsi/gomega
  go get -d github.com/cloudfoundry/cli
  cf_cli_set_version
  cf_cli_generate_language_resources
  update_godeps
}

cf_cli_set_version() {
  pushd "$GOPATH/src/github.com/cloudfoundry/cli"
    git checkout "$CF_CLI_VERSION"
  popd
}

cf_cli_generate_language_resources() {
  pushd "$GOPATH/src/github.com/cloudfoundry/cli"
    bin/generate-language-resources
  popd
}

update_godeps() {
  rm -fR Godeps
  godep save ./...
}

main
